version: '3.8'

services:
    postgres:
        image: postgres:13
        container_name: budget-planner-postgres
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
        ports:
            - '5336:5432'
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
